### ISSUE TITLE
Dataset is unavailable

### ISSUE THREAD

**Issue by qiyan98** [eyildiz-ugoe/screw_detection#3]
Hi, the dataset at this [link](https://owncloud.gwdg.de/index.php/s/AJ7W6t1nrIxYnol) is no longer available. Would you please have a look into it?

**Comment by romulofff** [comment]
Hi, I'm also interested on the dataset, still unavailable, could you guys provide a new link?

**Comment by eyildiz-ugoe** [comment]
Hi. The code has changed much since the release. We do not use the dataset as it was anymore, we rather created a [TFrecord](https://zenodo.org/record/4727706#.Yr72EHhBzJU) to do it. Of course, the code has to be changed accordingly.

**Comment by Xonxt** [comment]
> Hi. The code has changed much since the release. We do not use the dataset as it was anymore, we rather created a [TFrecord](https://zenodo.org/record/4727706#.Yr72EHhBzJU) to do it. Of course, the code has to be changed accordingly.

Hi, do you have an example of code for reading your TFRecord dataset correctly?

**Comment by FrankARicardo** [comment]
Hi. Could you please set as public de original dataset? I am working in a similar problem and need images like those.
Thanks

**Comment by eyildiz-ugoe** [comment]
> Hi. Could you please set as public de original dataset? I am working in a similar problem and need images like those. Thanks

The TFRecords are already public.

**Comment by FrankARicardo** [comment]
Thank you very much. I decode them to use the images

**Comment by FrankARicardo** [comment]
> 
#features of the TFRecord
image_feature_description = {
    'label': tf.io.FixedLenFeature([], tf.int64),
    'image': tf.io.FixedLenFeature([], tf.string),
}

#Parse function
def _parse_image_function(example_proto):
  return tf.io.parse_single_example(example_proto, image_feature_description)

#reading and parsing the TFRecord
raw_image_dataset = tf.data.TFRecordDataset("PATH") 
parsed_image_dataset = raw_image_dataset.map(_parse_image_function) 

for image_features in parsed_image_dataset: 
    image_raw = image_features['image'].numpy()
    label = str(image_features['label'].numpy())
    image = Image.open(io.BytesIO(image_raw))

#now you have the label and the image

**Comment by shrutic12** [comment]
> def _parse_image_function(example_proto): return tf.io.parse_single_example(example_proto, image_feature_description)
> 
> #reading and parsing the TFRecord raw_image_dataset = tf.data.TFRecordDataset("PATH") parsed_image_dataset = raw_image_dataset.map(_parse_image_function)
> 
> for image_features in parsed_image_dataset: image_raw = image_features['image'].numpy() label = str(image_features['label'].numpy()) image = Image.open(io.BytesIO(image_raw))

Hello! I am trying to get access to the dataset using the code above, however, I get this error message :

`{{function_node __wrapped__IteratorGetNext_output_types_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} corrupted record at 0 (Is this even a TFRecord file?) [Op:IteratorGetNext] name: `


Is the dataset still available to access? 


Here is the code : 

```
`def _parse_image_function(example_proto):
  return tf.io.parse_single_example(example_proto, image_feature_description)

#reading and parsing the TFRecord
raw_image_dataset = tf.data.TFRecordDataset(filename)
parsed_image_dataset = raw_image_dataset.map(_parse_image_function)

print(parsed_image_dataset)

for image_features in parsed_image_dataset:
  image_raw = image_features['image'].numpy()
  label = str(image_features['label'].numpy())
  plt.imshow(image_raw)`
```

**Comment by FrankARicardo** [comment]
Hello, are you using this lines?:

`
image_feature_description = {
'label': tf.io.FixedLenFeature([], tf.int64),
'image': tf.io.FixedLenFeature([], tf.string),
}`
